### ISSUE TITLE
Perimeter of rectangle is incorrect 

### ISSUE THREAD

**Issue by siddiquf** [comp491-Fall2020/github-issues-activity-f20#7]
The Calculator.rectPer method computes an incorrect value for rectangle perimeters.

**Comment by sonukushwaha403** [comment]
i would like to work in this issue, can you please assign it to me.

**Comment by studentsam** [comment]
I will fix this!

**Comment by hieu-t-tran** [comment]
Since there is no issue that is not yet commented, I will work on this issue as well.
